const actionTypes = {
  FETCH_WEATHER_REQUEST: "FETCH_WEATHER_REQUEST",
  FETCH_WEATHER_SUCCESS: "FETCH_WEATHER_SUCCESS",
  FETCH_WEATHER_ERROR: "FETCH_WEATHER_ERROR",
};

export default actionTypes;
